dataset = [
    {"question": "If you like someone right away, it is said that you have 'taken a' what 'to him'?",
     "options": ['⬥ A:Gloss', '⬥ B:Shine', '⬥ C:Glare', '⬥ D:Can of Reddi-wip'], "correct_answer": "Shine"},
    {"question": "A resident of a small town is said to be a 'local' what?",
     "options": ['⬥ A:Yogurt', '⬥ B:Yam', '⬥ C:Yokel', '⬥ D:Yoko Ono'], "correct_answer": "Yokel"},
    {"question": "A Brillo Pad is commonly used to do what?",
     "options": ['⬥ A:Mop the floor', '⬥ B:Clean pots and pans', '⬥ C:Heat food', '⬥ D:Exfoliate'],
     "correct_answer": "Clean pots and pans"},
    {"question": "On a standard hopscotch surface, what is usually drawn inside each square?",
     "options": ['⬥ A:Letter', '⬥ B:Number', '⬥ C:Star', '⬥ D:Stick figure'], "correct_answer": "Number"},
    {"question": "Which of these contractions is considered to be improper English?",
     "options": ["⬥ A:Don't", "⬥ B:Ain't", "⬥ C:Won't", "⬥ D:Can't"], "correct_answer": "Ain't"},
    {"question": "Which of the following gems is often classified as either natural or cultured?",
     "options": ['⬥ A:Pearl', '⬥ B:Emerald', '⬥ C:Ruby', '⬥ D:Diamond'], "correct_answer": "Pearl"},
    {"question": "Which of these crops is most likely to be harvested using a combine?",
     "options": ['⬥ A:Cabbage', '⬥ B:Wheat', '⬥ C:Grapes', '⬥ D:Apples'], "correct_answer": "Wheat"},
    {"question": "Known for its artist community, the town of Taos is located in what U.S. state?",
     "options": ['⬥ A:Arizona', '⬥ B:Oregon', '⬥ C:Colorado', '⬥ D:New Mexico'], "correct_answer": "New Mexico"},
    {"question": "In his 1998  song 'Hard Knock Life,' Jay-Z samples a song from what Broadway musical?",
     "options": ['⬥ A:A Chorus Line', '⬥ B:42nd Street', '⬥ C:Annie', '⬥ D:West Side Story'],
     "correct_answer": "Annie"},
    {"question": "On the TV series 'Crossing Jordan,' what is the title character's occupation?",
     "options": ['⬥ A:Defense attorney', '⬥ B:Child psychologist', '⬥ C:Private investigator', '⬥ D:Medical examiner'],
     "correct_answer": "Medical examiner"},
    {"question": "What dinosaur gets its name from the Latin words meaning 'swift robber'?",
     "options": ['⬥ A:Triceratops', '⬥ B:Stegosaurus', '⬥ C:Velociraptor', '⬥ D:Tyrannosaurus'],
     "correct_answer": "Velociraptor"},
    {"question": "In 1977, Janet Guthrie became the first woman to compete in what sporting event?",
     "options": ["⬥ A:America's Cup", '⬥ B:Kentucky Derby', '⬥ C:Indy 500', '⬥ D:Boston Marathon'],
     "correct_answer": "Indy 500"},
    {"question": "What is the dot over the letter 'i' called?'Phone-a-Friend' and '50:50'lifelinesused.",
     "options": ['⬥ A:Abb', '⬥ B:Tittle', '⬥ C:Dation', '⬥ D:Blip'], "correct_answer": "Tittle"},
    {"question": "The Reina Sofia Art Center is located in what European city?'50:50' lifeline used",
     "options": ['⬥ A:Madrid', '⬥ B:Lisbon', '⬥ C:Rome', '⬥ D:Vienna'], "correct_answer": "Madrid"},
    {
        "question": "When Charles Lindbergh made the first nonstop transatlantic flight, he flew between which two cities?'50:50' lifeline used",
        "options": ['⬥ A:Toronto and Stockholm', '⬥ B:Chicago and London', '⬥ C:Saint Louis and Dublin',
                    '⬥ D:New York and Paris'], "correct_answer": "New York and Paris"},
    {"question": "What kind of food is pastrami?'50:50' lifeline used",
     "options": ['⬥ A:dried salmon', '⬥ B:smoked beef', '⬥ C:cured ham', '⬥ D:salted bacon'],
     "correct_answer": "smoked beef"},
    {"question": "Which of these appears on the reverse of a twenty dollar bill?'50:50' lifeline used",
     "options": ['⬥ A:Lincoln Memorial', '⬥ B:U.S. Capitol', '⬥ C:White House', '⬥ D:U.S. Treasury'],
     "correct_answer": "White House"},
    {
        "question": "Traditionally, what is the only occasion when alcohol is allowed into the chamber of the House of Commons?'50:50' and 'Ask the Audience' lifelines used",
        "options": ["⬥ A:PM's question time", '⬥ B:Budget Speech', '⬥ C:State opening', '⬥ D:Election of new Speaker'],
        "correct_answer": "Budget Speech"},
    {"question": "New Sarum is the former name of which city?'50:50' and 'Ask the Audience' lifelines used",
     "options": ['⬥ A:Salisbury', '⬥ B:Stoke-on-Trent', '⬥ C:Shrewsbury', '⬥ D:Sheffield'],
     "correct_answer": "Salisbury"},
    {"question": "Jiffy Pop is a popular brand of what?",
     "options": ['⬥ A:Popcorn', '⬥ B:Soft drink', '⬥ C:Popsicle', '⬥ D:Viagra'], "correct_answer": "Popcorn"},
    {"question": "In the 1975 movie 'Jaws', what kind of shark is the title character?",
     "options": ['⬥ A:Mako shark', '⬥ B:Hammerhead shark', '⬥ C:Great white shark', '⬥ D:Tiger shark'],
     "correct_answer": "Great white shark"},
    {
        "question": "In its U.S. version, which of these board games requires you to collect six wedge-shaped pieces to win?",
        "options": ['⬥ A:Risk', '⬥ B:Trivial Pursuit', '⬥ C:Life', '⬥ D:Candy Land'],
        "correct_answer": "Trivial Pursuit"},
    {"question": "A blindfolded woman carrying a scale is traditionally used to represent which of these concepts?",
     "options": ['⬥ A:Justice', '⬥ B:Liberty', '⬥ C:Wisdom', '⬥ D:Community'], "correct_answer": "Justice"},
    {"question": "The period known as the Renaissance takes its name from a word meaning what?",
     "options": ['⬥ A:Enlightenment', '⬥ B:Truth', '⬥ C:Rebirth', '⬥ D:Victory'], "correct_answer": "Rebirth"},
    {"question": "People would most likely use the mnemonic 'Every good boy does fine' when doing what?",
     "options": ['⬥ A:Learning geography', '⬥ B:Reading music', '⬥ C:Reading Latin', '⬥ D:Learning to type'],
     "correct_answer": "Reading music"},
    {"question": "What is the national capital of Canada?",
     "options": ['⬥ A:Winnipeg', '⬥ B:Calgary', '⬥ C:Edmonton', '⬥ D:Ottawa'], "correct_answer": "Ottawa"},
    {"question": "In the U.S., how many tablespoons are in a cup?'Ask the Audience' and '50:50' lifelines used",
     "options": ['⬥ A:12', '⬥ B:16', '⬥ C:18', '⬥ D:24'], "correct_answer": "16"},
    {"question": "In the human body, adrenaline is produced by glands located on top of which of these organs?",
     "options": ['⬥ A:Lungs', '⬥ B:Liver', '⬥ C:Stomach', '⬥ D:Kidneys'], "correct_answer": "Kidneys"},
    {
        "question": "Which of these scientists became famous for his theoretical work on black holes?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Carl Sagan', '⬥ B:Richard Feynman', '⬥ C:Stephen Hawking', '⬥ D:Freeman Dyson'],
        "correct_answer": "Stephen Hawking"},
    {
        "question": "What U.S. Senator was known as 'The Great Compromiser' for his efforts to keep the Union from dividing?",
        "options": ['⬥ A:Daniel Webster', '⬥ B:Stephen Douglas', '⬥ C:John C. Calhoun', '⬥ D:Henry Clay'],
        "correct_answer": "Henry Clay"},
    {"question": "Which of these articles of clothing is usually held in place by straps tied around the neck?",
     "options": ['⬥ A:Camisole', '⬥ B:Tank Top', '⬥ C:Halter Top', '⬥ D:Straitjacket'], "correct_answer": "Halter Top"},
    {"question": "The sequel to what popular 1990s movie is subtitled 'Back in the Habit'?",
     "options": ['⬥ A:Batman', '⬥ B:Ghost', '⬥ C:Home Alone', '⬥ D:Sister Act'], "correct_answer": "Sister Act"},
    {"question": "Children usually experience discomfort known as 'growing pains' in what part of the body?",
     "options": ['⬥ A:Neck', '⬥ B:Shoulders', '⬥ C:Legs', '⬥ D:Wrists'], "correct_answer": "Legs"},
    {
        "question": "In the classic TV ads, what was the usual answe to the question 'Pardon me, but do you have any Grey Poupon?'",
        "options": ['⬥ A:Surely I do', '⬥ B:But of course', '⬥ C:Well let me check', '⬥ D:Say please'],
        "correct_answer": "But of course"},
    {
        "question": "Introduced in 2001, Harmony is a breakfast cereal targeted toward what category of consumer?'Ask The Audience' lifeline used",
        "options": ['⬥ A:Women', '⬥ B:Kids', '⬥ C:Seniors', '⬥ D:Athletes'], "correct_answer": "Women"},
    {"question": "Publisher John Bartlett is best known for his 1855 book titled 'Familiar' what?'50:50' lifeline used",
     "options": ['⬥ A:Birds', '⬥ B:Familiy names', '⬥ C:Quotations', '⬥ D:Cities'], "correct_answer": "Quotations"},
    {
        "question": "Who served as U.S. vice president under President Dwight D. Eisenhower?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Nelson Rockefeller', '⬥ B:Spiro Agnew', '⬥ C:Lyndon Johnson', '⬥ D:Richard Nixon'],
        "correct_answer": "Richard Nixon"},
    {"question": "Break dancing is most often performed to what type of music?",
     "options": ['⬥ A:Rap', '⬥ B:Country', '⬥ C:Classical', '⬥ D:The theme to “Jeopardy”'], "correct_answer": "Rap"},
    {"question": "What additional flavoring gives the soft drink Pepsi Twist its “twist”?",
     "options": ['⬥ A:Cherry', '⬥ B:Vanilla', '⬥ C:Ginger', '⬥ D:Lemon'], "correct_answer": "Lemon"},
    {"question": "Hospital “candy stripers” were named for their uniforms which features what color stripes?",
     "options": ['⬥ A:Red and white', '⬥ B:Blue and green', '⬥ C:Orange and yellow', '⬥ D:Purple and gold'],
     "correct_answer": "Red and white"},
    {"question": "Sherpas are people known for their ability to lead treks through what mountains?",
     "options": ['⬥ A:Andes', '⬥ B:Himalayas', '⬥ C:Rockies', '⬥ D:Alps'], "correct_answer": "Himalayas"},
    {"question": "The Kentucky Derby is also known as the “Run for the” what?",
     "options": ['⬥ A:Money', '⬥ B:Rainbow', '⬥ C:Roses', '⬥ D:Gold'], "correct_answer": "Roses"},
    {
        "question": "In the Wham! song “Wake Me Up Before You Go Go,” what dance is mentioned repeatedly?'Ask the Audience' lifeline used",
        "options": ['⬥ A:Rumba', '⬥ B:Merengue', '⬥ C:Jitterbug', '⬥ D:Can-can'], "correct_answer": "Jitterbug"},
    {"question": "What TV comedian’s signatures sign-off was “Good night, Mrs Calabash, wherever you are”?",
     "options": ['⬥ A:Jimmy Durante', '⬥ B:Jack Benny', '⬥ C:George Burns', '⬥ D:Sid Caesar'],
     "correct_answer": "Jimmy Durante"},
    {"question": "Edmond Dantès is a fictional character better known by what name?",
     "options": ['⬥ A:Zorba the Greek', '⬥ B:The Count of Monte Cristo', '⬥ C:The Merchant of Venice', '⬥ D:The Idiot'],
     "correct_answer": "The Count of Monte Cristo"},
    {"question": "The Fujita Scale measures the amount of damage caused by what natural disaster?",
     "options": ['⬥ A:Tornado', '⬥ B:Forest fire', '⬥ C:Flood', '⬥ D:Earthquake'], "correct_answer": "Tornado"},
    {
        "question": "In a famous movie scene, Mae West says, “Why don’t you come up sometime and see me?” to what actor?’Phone-a-Friend' and ’50:50’ lifelines used",
        "options": ['⬥ A:Gary Cooper', '⬥ B:Clark Gable', '⬥ C:Cary Grant', '⬥ D:Montgomery Clift'],
        "correct_answer": "Cary Grant"},
    {"question": "“To serve, not to be served” is the motto of what organization?",
     "options": ['⬥ A:AARP', '⬥ B:American Red Cross', '⬥ C:Salvation Army', '⬥ D:NAACP'], "correct_answer": "AARP"},
    {
        "question": "In their best-selling advice books, 'The Beardstown Ladies' claimed to have abnormal success with what?'50:50' Lifeline used",
        "options": ['⬥ A:Finding romance', '⬥ B:Losing weight', '⬥ C:Picking stocks', '⬥ D:Maintaining youth'],
        "correct_answer": "Picking stocks"},
    {"question": "Anthracite is a highly pure form of what substance?'Phone a Friend' Lifeline used",
     "options": ['⬥ A:Coal', '⬥ B:Marble', '⬥ C:Iron', '⬥ D:Quartz'], "correct_answer": "Coal"},
    {"question": "The twelve signs of the zodiac are named after what?",
     "options": ['⬥ A:Constellations', '⬥ B:Rivers', '⬥ C:Rock formations', '⬥ D:Strip malls'],
     "correct_answer": "Constellations"},
    {
        "question": "On the TV game show 'The Price is Right,' contestants do what to try to get into the 'Showcase Showdown'?",
        "options": ['⬥ A:Pick a card', '⬥ B:Spin a large wheel', '⬥ C:Choose a door', '⬥ D:Roll a pair of dice'],
        "correct_answer": "Spin a large wheel"},
    {"question": "In 1996, what rock band resumed wearing its trademark black-and-white makeup?",
     "options": ['⬥ A:AC/DC', '⬥ B:Black Sabbath', '⬥ C:Aerosmith', '⬥ D:Kiss'], "correct_answer": "Kiss"},
    {"question": "A famous WWII battle site, Iwo Jima is an island of what country?'Ask the Audience' lifeline used",
     "options": ['⬥ A:Japan', '⬥ B:United States', '⬥ C:China', '⬥ D:Philippines'], "correct_answer": "Japan"},
    {"question": "Folk hero Paul Bunyan was companions with Babe, a giant blue what?",
     "options": ['⬥ A:Ox', '⬥ B:Bear', '⬥ C:Mountain lion', '⬥ D:Wolf'], "correct_answer": "Ox"},
    {"question": "What pro wrestler's signature facial expression is called 'The People's Eyebrow'?",
     "options": ['⬥ A:Goldberg', '⬥ B:Stone Cold Steve Austin', '⬥ C:The Rock', '⬥ D:Mick Foley'],
     "correct_answer": "The Rock"},
    {"question": "Which of these 'nuts' is actually a legume?'50:50' lifeline used",
     "options": ['⬥ A:Peanut', '⬥ B:Cashew', '⬥ C:Chestnut', '⬥ D:Beechnut'], "correct_answer": "Peanut"},
    {"question": "In golf, scoring one stroke under par on a hole is called a what?",
     "options": ['⬥ A:Doggie', '⬥ B:Duckie', '⬥ C:Birdie', '⬥ D:Miracle'], "correct_answer": "Birdie"},
    {"question": "The childhood prank known as a 'wet willie' involves putting a wet finger in someone's what?",
     "options": ['⬥ A:Ear', '⬥ B:Armpit', '⬥ C:Nose', '⬥ D:Belly button'], "correct_answer": "Ear"},
    {"question": "What business's name is a term for a small, economically dependent country?",
     "options": ['⬥ A:Tropicana', '⬥ B:Banana Republic', '⬥ C:Crate & Barrel', '⬥ D:Aeropostale'],
     "correct_answer": "Banana Republic"},
    {"question": "A popular ad campaign for Lubriderm skin care lotions features what animal?",
     "options": ['⬥ A:Alligator', '⬥ B:Porcupine', '⬥ C:Camel', '⬥ D:Dolphin'], "correct_answer": "Alligator"},
    {"question": "In January 2002, President George W. Bush fainted and bruised his cheek after choking on what?",
     "options": ['⬥ A:Pretzel', '⬥ B:Chicken wing', '⬥ C:Apple', '⬥ D:Carrot'], "correct_answer": "Pretzel"},
    {
        "question": "In 1896, Bostonian Fannie Farmer published a classic book on what subject?‘Ask the Audience’ lifeline used",
        "options": ['⬥ A:Etiquette', '⬥ B:Fashion', '⬥ C:Grammar', '⬥ D:Cooking'], "correct_answer": "Cooking"},
    {"question": "What layer of the Earth's atmosphere is farthest from its surface?",
     "options": ['⬥ A:Stratosphere', '⬥ B:Exosphere', '⬥ C:Thermosphere', '⬥ D:Troposphere'],
     "correct_answer": "Exosphere"},
    {"question": "Flokati and kilim are popular types of what home furnishing?'50:50' lifeline used",
     "options": ['⬥ A:Hanging lamps', '⬥ B:Draperies', '⬥ C:Rugs', '⬥ D:Vases'], "correct_answer": "Rugs"},
    {"question": "The first band John Lennon and Paul McCartney played together was named what?",
     "options": ['⬥ A:The Quarrymen', '⬥ B:The Merseybeats', '⬥ C:The Undertakers', '⬥ D:The Big Three'],
     "correct_answer": "The Quarrymen"},
    {"question": "What movie studio's logo features the slogan “Ars Gratia Artis,” meaning “Art for Art's Sake”?",
     "options": ['⬥ A:Paramount', '⬥ B:Universal', '⬥ C:MGM', '⬥ D:Columbia'], "correct_answer": "MGM"},
    {
        "question": "Found in many animals, Jacobson's organ is a cavity to do which of the following?‘Phone-a-Friend’ lifeline used",
        "options": ['⬥ A:Smell', '⬥ B:Swim', '⬥ C:Digest', '⬥ D:See'], "correct_answer": "Smell"},
    {"question": "In which of these countries do motorists normally drive on the right-hand side of the street?",
     "options": ['⬥ A:Thailand', '⬥ B:Japan', '⬥ C:Indonesia', '⬥ D:Brazil'], "correct_answer": "Brazil"},
    {
        "question": "Who was the first U.S. president to be elected with the assistance of women visitors?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Theodore Roosevelt', '⬥ B:William Howard Taft', '⬥ C:Woodrow Wilson', '⬥ D:Warren G. Harding'],
        "correct_answer": "Warren G. Harding"},
    {"question": "Acupuncture is an alternative medicinal practice that uses what to treat the body?",
     "options": ['⬥ A:Hot stones', '⬥ B:Herbal potions', '⬥ C:Needles', '⬥ D:Häagen-Dazs'],
     "correct_answer": "Needles"},
    {"question": "Ward and June are the names of the parents on what classic TV series?",
     "options": ['⬥ A:Leave It To Beaver', '⬥ B:Dennis the Menace', '⬥ C:Father Knows Best', '⬥ D:Petticoat Junction'],
     "correct_answer": "Leave It To Beaver"},
    {"question": "The Texas city Corpus Christi gets its name from a Latin phrase meaning 'the' what 'of Christ'?",
     "options": ['⬥ A:Spirit', '⬥ B:Word', '⬥ C:Touch', '⬥ D:Body'], "correct_answer": "Body"},
    {
        "question": "Which of these keys on a standard keyboard is traditionally typed using the thumb?'50:50' lifeline used",
        "options": ['⬥ A:Return key', '⬥ B:Space bar', '⬥ C:Tab key', '⬥ D:Shift key'], "correct_answer": "Space bar"},
    {"question": "In the Northern Hemisphere, the harvest moon is the full moon nearest which of these days?",
     "options": ['⬥ A:Vernal equinox', '⬥ B:Summer solstice', '⬥ C:Autumnal equinox', '⬥ D:Winter solstice'],
     "correct_answer": "Autumnal equinox"},
    {
        "question": "Internet provider AOL offers an online chat service called 'Instant' what?'Ask the Audience' lifeline used",
        "options": ['⬥ A:Friend', '⬥ B:Correspondence', '⬥ C:Messenger', '⬥ D:Headache'],
        "correct_answer": "Messenger"},
    {"question": "On the TV series 'The Munsters', Herman Munster resembles what legendary monster?",
     "options": ['⬥ A:Frankenstein', '⬥ B:The Mummy', '⬥ C:Dracula', '⬥ D:Werewolf'], "correct_answer": "Frankenstein"},
    {"question": "'Unterseeboot' is the German word for what kind of vessel?",
     "options": ['⬥ A:Steamboat', '⬥ B:Submarine', '⬥ C:Rowboat', '⬥ D:Ocean liner'], "correct_answer": "Submarine"},
    {"question": "Who is President George W. Bush's Press Secretary?",
     "options": ['⬥ A:Andrew Card', '⬥ B:Karen Hughes', '⬥ C:Karl Rove', '⬥ D:Ari Fleischer'],
     "correct_answer": "Ari Fleischer"},
    {"question": "The game tic-tac-toe is also known by what name?",
     "options": ['⬥ A:Sticks & stones', '⬥ B:Noughts & crosses', '⬥ C:Bits & pieces', '⬥ D:Hugs & kisses'],
     "correct_answer": "Noughts & crosses"},
    {"question": "What kind of geological formation is an archipelago?",
     "options": ['⬥ A:Chain of Islands', '⬥ B:Intersecting rivers', '⬥ C:Volcanic crater', '⬥ D:Mountain range'],
     "correct_answer": "Chain of Islands"},
    {
        "question": "What restaurant chain offers a signature meal called the Rooty Tooty Fresh 'N Fruity?'Phone-a-Friend' lifeline used",
        "options": ["⬥ A:Denny's", "⬥ B:Chili's", "⬥ C:T.G.I. Friday's", '⬥ D:IHOP'], "correct_answer": "IHOP"},
    {"question": "Which of these children's games requires kids to hold each others' hands?",
     "options": ['⬥ A:Duck Duck Goose', '⬥ B:Hopscotch', '⬥ C:Red Rover', '⬥ D:Crossing the Freeway'],
     "correct_answer": "Red Rover"},
    {"question": "In 1971, the Animal Welfare Institute launched its famous campaign to 'Save the' what?",
     "options": ['⬥ A:Whales', '⬥ B:Bears', '⬥ C:Eagles', '⬥ D:Chimpanzees'], "correct_answer": "Whales"},
    {"question": "What does the 'P' stand for in the international organization name 'OPEC'?",
     "options": ['⬥ A:Peace', '⬥ B:Petroleum', '⬥ C:Power', '⬥ D:Political'], "correct_answer": "Petroleum"},
    {"question": "In the Northern Hemisphere, the longest day of the year occurs during what month?",
     "options": ['⬥ A:May', '⬥ B:June', '⬥ C:July', '⬥ D:August'], "correct_answer": "June"},
    {"question": "World War II began on September 1, 1939 when Germany invaded what country?",
     "options": ['⬥ A:Poland', '⬥ B:France', '⬥ C:Belgium', '⬥ D:USSR'], "correct_answer": "Poland"},
    {
        "question": "In the 1860s, French scientist Louis Pasteur invented a process used to sterilize which of the following?",
        "options": ['⬥ A:Water', '⬥ B:Aspirin', '⬥ C:Milk', '⬥ D:Mrs. Pasteur'], "correct_answer": "Milk"},
    {"question": "In the U.S., Thanksgiving falls on what day of the week?",
     "options": ['⬥ A:Sunday', '⬥ B:Tuesday', '⬥ C:Thursday', '⬥ D:Friday'], "correct_answer": "Thursday"},
    {"question": "Which of these musical instruments has small hammers inside of it?",
     "options": ['⬥ A:Piano', '⬥ B:Cello', '⬥ C:Oboe', '⬥ D:Accordion'], "correct_answer": "Piano"},
    {
        "question": "On June 30, 2002, the U.S. Postal Service raised the price of a First-Class stamp from 34 cents to what?'Ask the Audience' lifeline used",
        "options": ['⬥ A:36 cents', '⬥ B:37 cents', '⬥ C:38 cents', '⬥ D:39 cents'], "correct_answer": "37 cents"},
    {"question": "In mathematics, the binary number system uses what number as its base?",
     "options": ['⬥ A:1', '⬥ B:2', '⬥ C:5', '⬥ D:10'], "correct_answer": "2"},
    {"question": "Which TV animal breathes through a blowhole?",
     "options": ['⬥ A:Flipper', '⬥ B:Lassie', '⬥ C:Mr. Ed', "⬥ D:Bill O'Reilly"], "correct_answer": "Flipper"},
    {"question": "Whose picture is on the $100 bill?",
     "options": ['⬥ A:Patrick Henry', '⬥ B:Samuel Adams', '⬥ C:John Hancock', '⬥ D:Benjamin Franklin'],
     "correct_answer": "Benjamin Franklin"},
    {"question": "What would you use a loofah to do?",
     "options": ['⬥ A:Mix a drink', '⬥ B:Take a shower', '⬥ C:Trim a hedge', '⬥ D:Knit a sweater'],
     "correct_answer": "Take a shower"},
    {"question": "What melted the Wicked Witch of the West?",
     "options": ['⬥ A:Sunlight', '⬥ B:Music', '⬥ C:Water', '⬥ D:Fire'], "correct_answer": "Water"},
    {"question": "In Chicago's song 'Saturday in the Park', what day is it?",
     "options": ['⬥ A:First day of spring', '⬥ B:Fourth of July', '⬥ C:Some time in May', '⬥ D:Halloween'],
     "correct_answer": "Fourth of July"},
    {"question": "What coach said 'Winning isn't everything, it's the only thing'?",
     "options": ['⬥ A:Vince Lombardi', '⬥ B:George Halas', '⬥ C:Knute Rockne', '⬥ D:Bear Bryant'],
     "correct_answer": "Vince Lombardi"},
    {"question": "A mixture of two metals is a what?",
     "options": ['⬥ A:Tincture', '⬥ B:Alloy', '⬥ C:Emulsion', '⬥ D:Suspension'], "correct_answer": "Alloy"},
    {"question": "What would not be treated by an otolaryngologist?",
     "options": ['⬥ A:Throat', '⬥ B:Nose', '⬥ C:Eye', '⬥ D:Ear'], "correct_answer": "Eye"},
    {"question": "What color is the center square in the game Scrabble?'Ask the Audience' and '50:50' lifelines used",
     "options": ['⬥ A:Red', '⬥ B:Pink', '⬥ C:Dark blue', '⬥ D:Light blue'], "correct_answer": "Pink"},
    {"question": "Often used with fireplaces, a bellows is a device that forcibly expels what?",
     "options": ['⬥ A:Water', '⬥ B:Sand', '⬥ C:Air', '⬥ D:Romance'], "correct_answer": "Air"},
    {"question": "In the Boy Scouts of America, what is the highest rank a scout can achieve?",
     "options": ['⬥ A:Eagle', '⬥ B:Lion', '⬥ C:Bear', '⬥ D:Wolf'], "correct_answer": "Eagle"},
    {
        "question": "In what Broadway musical does a chorus of teens sing, 'Tell me more, tell me more, did you get very far'?'Ask the Audience' lifeline used",
        "options": ['⬥ A:West Side Story', '⬥ B:Bye Bye Birdie', '⬥ C:Grease', '⬥ D:Oliver!'],
        "correct_answer": "Grease"},
    {"question": "In the classic children's game 'Hungry Hungry Hippos,' what do the hippos eat?",
     "options": ['⬥ A:Dice', '⬥ B:Pegs', '⬥ C:Beanbags', '⬥ D:Marbles'], "correct_answer": "Marbles"},
    {"question": "Irish coffee is traditionally made with what liquor?'Phone-a-Friend' lifeline used",
     "options": ['⬥ A:Vodka', '⬥ B:Whiskey', '⬥ C:Gin', '⬥ D:Rum'], "correct_answer": "Whiskey"},
    {"question": "On the TV series 'Welcome Back, Kotter,' what does Horshack say when he raises his hand in class?",
     "options": ['⬥ A:Psst! Psst!', '⬥ B:Over here!', '⬥ C:Ooo! Ooo!', '⬥ D:Me! Me! Me!'],
     "correct_answer": "Ooo! Ooo!"},
    {
        "question": "In classical Greek architecture, what type of column is traditionally the most ornate?'50:50' lifeline used",
        "options": ['⬥ A:Ionic', '⬥ B:Tuscan', '⬥ C:Doric', '⬥ D:Corinthian'], "correct_answer": "Corinthian"},
    {"question": "Richard Nixon's pet dog Checkers was what breed?",
     "options": ['⬥ A:Beagle', '⬥ B:Cocker spaniel', '⬥ C:German shepherd', '⬥ D:Collie'],
     "correct_answer": "Cocker spaniel"},
    {"question": "The children's song 'The Hokey Pokey' ends with what line?",
     "options": ['⬥ A:I never had a doubt', "⬥ B:Why don't we all go out", "⬥ C:That's what it's all about",
                 "⬥ D:Who's got aspirin?"], "correct_answer": "That's what it's all about"},
    {"question": "A tomahawk is a small what?", "options": ['⬥ A:Knife', '⬥ B:Ax', '⬥ C:Club', '⬥ D:Spear'],
     "correct_answer": "Ax"},
    {"question": "What weather condition is often described as 'pea soup'?",
     "options": ['⬥ A:Hazy sun', '⬥ B:Thick fog', '⬥ C:Freezing rain', '⬥ D:Gusty winds'],
     "correct_answer": "Thick fog"},
    {"question": "In India, snake charmers traditionally charm what kind of snakes into dancing?",
     "options": ['⬥ A:Boa constrictors', '⬥ B:Adders', '⬥ C:Cobras', '⬥ D:Anacondas'], "correct_answer": "Cobras"},
    {"question": "Rivals Krystle and Alexis duke it out in a lily pond in a famous scene from what 1980s TV drama?",
     "options": ["⬥ A:Knot's Landing", '⬥ B:Falcon Crest', '⬥ C:Dallas', '⬥ D:Dynasty'], "correct_answer": "Dynasty"},
    {"question": "'Big Sky Country' is a popular nickname for what U.S. state?'Ask the Audience' lifeline used",
     "options": ['⬥ A:Idaho', '⬥ B:South Dakota', '⬥ C:Montana', '⬥ D:Wyoming'], "correct_answer": "Montana"},
    {"question": "By definition, an apéritif is a drink served when?",
     "options": ['⬥ A:Before a meal', '⬥ B:Before bedtime', '⬥ C:Before noon', '⬥ D:Before departing'],
     "correct_answer": "Before a meal"},
    {"question": "Since 1984, who has been the host of the TV game show 'Jeopardy!'?",
     "options": ['⬥ A:Monty Hall', '⬥ B:Wink Martindale', '⬥ C:Alex Trebek', "⬥ D:What's Jeopardy!?"],
     "correct_answer": "Alex Trebek"},
    {"question": "A long-running ad campaign instructs you to spend two months' salary on what?",
     "options": ['⬥ A:Rent', '⬥ B:Summer vacation', '⬥ C:Clothing', '⬥ D:Engagement ring'],
     "correct_answer": "Engagement ring"},
    {"question": "How many lines are there in a standard knock-knock joke?",
     "options": ['⬥ A:3', '⬥ B:4', '⬥ C:5', '⬥ D:6'], "correct_answer": "5"},
    {"question": "The show business question 'Will it play in Peoria?' refers to a town in what U.S. state?",
     "options": ['⬥ A:Illinois', '⬥ B:Kansas', '⬥ C:Iowa', '⬥ D:Nebraska'], "correct_answer": "Illinois"},
    {"question": "The 'E' in the federal agency acronym 'FEMA' stands for what?",
     "options": ['⬥ A:Energy', '⬥ B:Emergency', '⬥ C:Elections', '⬥ D:Education'], "correct_answer": "Emergency"},
    {
        "question": "On the TV series 'Night Court,' what is the nickname of the tall, bald bailiff?'Ask the Audience' lifeline used",
        "options": ['⬥ A:Bear', '⬥ B:Whale', '⬥ C:Moose', '⬥ D:Bull'], "correct_answer": "Bull"},
    {"question": "The Ireng River in Guyana borders what other South American country?“50:50” lifeline used",
     "options": ['⬥ A:Brazil', '⬥ B:Suriname', '⬥ C:?', '⬥ D:?'], "correct_answer": "Brazil"},
    {"question": "In the classic cartoons, what is Bugs Bunny's signature greeting?",
     "options": ["⬥ A:What's up, doc?", '⬥ B:Howdy, partner', "⬥ C:What's new, pussycat?", "⬥ D:That's no carrot..."],
     "correct_answer": "What's up, doc?"},
    {"question": "In which of these high school classes are students most likely to use a petri dish?",
     "options": ['⬥ A:Physics', '⬥ B:Home economics', '⬥ C:Biology', '⬥ D:Physical education'],
     "correct_answer": "Biology"},
    {"question": "Which of these animals can change the color of its skin, depending on its mood and environment?",
     "options": ['⬥ A:Lion', '⬥ B:Octopus', '⬥ C:Zebra', '⬥ D:Elephant'], "correct_answer": "Octopus"},
    {"question": "Brothers Dennis, Carl and Brian Wilson were founding members of what pop band?",
     "options": ['⬥ A:The Beach Boys', '⬥ B:The Mamas & the Papas', '⬥ C:The Turtles', "⬥ D:The Lovin' Spoonful"],
     "correct_answer": "The Beach Boys"},
    {"question": "Mesquite is a type of wood traditionally used in what method of cooking?",
     "options": ['⬥ A:Stir-fry', '⬥ B:Braising', '⬥ C:Fondue', '⬥ D:Barbecue'], "correct_answer": "Barbecue"},
    {
        "question": "Where on the body would you normally find a 'soul patch'?'Ask the Audience' and '50:50' lifelines used",
        "options": ['⬥ A:Under the navel', '⬥ B:Above the chin', '⬥ C:Around the elbows', '⬥ D:Behind the ears'],
        "correct_answer": "Above the chin"},
    {"question": "The Ficus elastica is a common houseplant better known by what name?",
     "options": ['⬥ A:Spider plant', '⬥ B:Jade plant', '⬥ C:Zebra plant', '⬥ D:Rubber plant'],
     "correct_answer": "Rubber plant"},
    {"question": "A popular site for pilgrimages, the Wailing Wall is located in what city?",
     "options": ['⬥ A:Mecca', '⬥ B:Rome', '⬥ C:Cairo', '⬥ D:Jerusalem'], "correct_answer": "Jerusalem"},
    {
        "question": "In the 1984 movie 'The Karate Kid,' Daniel's tournament-winning kick shares its name with what bird?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Eagle', '⬥ B:Hawk', '⬥ C:Crane', '⬥ D:Falcon'], "correct_answer": "Crane"},
    {"question": "Weighing around three pounds, what is the heaviest internal organ in the human body?",
     "options": ['⬥ A:Pancreas', '⬥ B:Liver', '⬥ C:Heart', '⬥ D:Spleen'], "correct_answer": "Liver"},
    {"question": "The word 'maverick' comes from the name of an American pioneer who refused to do what?",
     "options": ['⬥ A:Use barbed wire', '⬥ B:Shoot wild animals', '⬥ C:Brand his cows', '⬥ D:Pay his taxes'],
     "correct_answer": "Brand his cows"},
    {
        "question": "Issued in 1934 for use by Federal Reserve banks, the $100,000 bill features what U.S. president on its front?",
        "options": ['⬥ A:James Monroe', '⬥ B:James Madison', '⬥ C:Theodore Roosevelt', '⬥ D:Woodrow Wilson'],
        "correct_answer": "Woodrow Wilson"},
    {"question": "According to a popular nursery rhyme, who was “eating her curds and whey”?",
     "options": ['⬥ A:Old Mother Hubbard', '⬥ B:Little Bo-peep', '⬥ C:Little Miss Muffet', '⬥ D:Jenny Craig'],
     "correct_answer": "Little Miss Muffet"},
    {"question": "“Grease monkey” is slang for a person who works as a what?",
     "options": ['⬥ A:Mechanic', '⬥ B:Barber', '⬥ C:Short-order cook', '⬥ D:Coal miner'], "correct_answer": "Mechanic"},
    {"question": "Founded in Hawaii in 1851, the Dole Food Company began as a grower of what fruit?",
     "options": ['⬥ A:Peach', '⬥ B:Watermelon', '⬥ C:Orange', '⬥ D:Pineapple'], "correct_answer": "Pineapple"},
    {"question": "Which of these expressions is an example of an oxymoron?",
     "options": ['⬥ A:Golden opportunity', '⬥ B:Downward spiral', '⬥ C:Living dead', '⬥ D:Change of heart'],
     "correct_answer": "Living dead"},
    {"question": "What 1970s  TV series title character has the last name Morgenstern?",
     "options": ['⬥ A:Alice', '⬥ B:Rhoda', '⬥ C:Maude', '⬥ D:Phyllis'], "correct_answer": "Rhoda"},
    {
        "question": "What sci-fi author wrote “Journey to the Center of the Earth” and “Around the World in Eighty Days”?'Ask the Audience' lifeline used",
        "options": ['⬥ A:H.G. Wells', '⬥ B:Edgar Rice Burroughs', '⬥ C:Jules Verne', '⬥ D:Ray Bradbury'],
        "correct_answer": "Jules Verne"},
    {
        "question": "Due to a controversy over nude photos, what state initially sent two women to the 2002 Miss America pageant?",
        "options": ['⬥ A:Texas', '⬥ B:Colorado', '⬥ C:Iowa', '⬥ D:North Carolina'], "correct_answer": "North Carolina"},
    {"question": "What animal is mentioned in the opening lines of the classic song “Mack the Knife”?",
     "options": ['⬥ A:Fox', '⬥ B:Tiger', '⬥ C:Shark', '⬥ D:Snake'], "correct_answer": "Shark"},
    {"question": "What retailer is known for its flexible work program aimed at Olympic hopefuls?",
     "options": ['⬥ A:Home Depot', '⬥ B:Wal-Mart', '⬥ C:Target', '⬥ D:Barnes & Noble'], "correct_answer": "Home Depot"},
    {"question": "What father and son won Academy Awards for the same movie?’Phone-a-Friend‘ lifeline used",
     "options": ['⬥ A:Henry & Peter Fonda', '⬥ B:Jason & Sam Robards', '⬥ C:Walter & John Huston',
                 '⬥ D:Kirk & Michael Douglas'], "correct_answer": "Walter & John Huston"},
    {"question": "“Nanuq” is the Inuit word for what animal?’50:50’ lifeline used",
     "options": ['⬥ A:Seal', '⬥ B:Polar bear', '⬥ C:Wolf', '⬥ D:Whale'], "correct_answer": "Polar bear"},
    {
        "question": "According to its label, Murphy Oil Soap 'Safety Cleans' what surface?'Ask the Audience' lifeline used",
        "options": ['⬥ A:Cement', '⬥ B:Marble', '⬥ C:Wood', '⬥ D:Glass'], "correct_answer": "Wood"},
    {"question": "According to an old saying, 'Possession is nine-tenths of the' what?",
     "options": ['⬥ A:Law', '⬥ B:Business', '⬥ C:Pleasure', '⬥ D:Battle'], "correct_answer": "Law"},
    {"question": "By definition, a nocturne is a work of art depicting what?",
     "options": ['⬥ A:Day', '⬥ B:Night', '⬥ C:Heaven', '⬥ D:Nature'], "correct_answer": "Day"},
    {"question": "Since 1983, who has been the sole anchor of 'NBC Nightly News'?'50:50' lifeline used",
     "options": ['⬥ A:Tom Brokaw', '⬥ B:Bernard Shaw', '⬥ C:Ted Koppel', '⬥ D:David Brinkley'],
     "correct_answer": "Tom Brokaw"},
    {"question": "When the U.S. national anthem is played, it is customary for men to remove their what?",
     "options": ['⬥ A:Hats', '⬥ B:Jackets', '⬥ C:Neckties', '⬥ D:Toupees'], "correct_answer": "Hats"},
    {"question": "What is the nationality of children's book character Harry Potter?",
     "options": ['⬥ A:German', '⬥ B:American', '⬥ C:English', '⬥ D:French'], "correct_answer": "English"},
    {"question": "Headgear is a device often worn by teenagers to help do what?",
     "options": ['⬥ A:Lose weight', '⬥ B:Straighten teeth', '⬥ C:Prevent sunburn', '⬥ D:Improve hearing'],
     "correct_answer": "Straighten teeth"},
    {"question": "By definition, a translucent object allows what to pass through it?",
     "options": ['⬥ A:Electricity', '⬥ B:Water', '⬥ C:Air', '⬥ D:Light'], "correct_answer": "Light"},
    {"question": "According to the title of a 1985 Tears for Fears song, 'Everybody Wants to' do what?",
     "options": ['⬥ A:Sell Their Soul', '⬥ B:Make a Difference', '⬥ C:Rule the World', '⬥ D:Find Somebody'],
     "correct_answer": "Rule the World"},
    {"question": "Which of these islands shares its name with a popular computer language?",
     "options": ['⬥ A:Java', '⬥ B:Malta', '⬥ C:Crete', '⬥ D:Cyprus'], "correct_answer": "Java"},
    {"question": "A single term for members of the U.S. House of Representatives lasts how many years?",
     "options": ['⬥ A:2', '⬥ B:4', '⬥ C:6', '⬥ D:8'], "correct_answer": "2"},
    {
        "question": "Most of the over 800 known Dead Sea Scrolls are written in what language?'50:50' and 'Phone-a-Friend'lifelinesused",
        "options": ['⬥ A:Greek', '⬥ B:Hebrew', '⬥ C:Latin', '⬥ D:Sanskrit'], "correct_answer": "Hebrew"},
    {"question": "The U.S. tested its first atomic bomb in 1945 near what location?'Ask the Audience'lifelineused",
     "options": ['⬥ A:Amchitka, AK', '⬥ B:Hattiesburg, MS', '⬥ C:Alamogordo, NM', '⬥ D:Farmington, CO'],
     "correct_answer": "Alamogordo, NM"},
    {"question": "Jean Auel's 2002 book 'The Shelters of Stone' continues the series that began with what 1980 novel?",
     "options": ['⬥ A:The Clan of the Cave Bear', '⬥ B:The Name of the Rose', "⬥ C:Mistral's Daughter",
                 '⬥ D:The Lonesome Gods'], "correct_answer": "The Clan of the Cave Bear"},
    {"question": "A turophile is a gourmet who specializes in what kind of food?",
     "options": ['⬥ A:Caviar', '⬥ B:Fruit', '⬥ C:Chocolate', '⬥ D:Cheese'], "correct_answer": "Cheese"},
    {"question": "Queen Victoria's 1840 wedding is credited with popularizing what tradition?",
     "options": ['⬥ A:Tossing a bouquet', '⬥ B:White bridal gown', '⬥ C:Throwing rice', '⬥ D:Flower girls'],
     "correct_answer": "White bridal gown"},
    {
        "question": "Which of these movie stars is not mentioned in Madonna's 1990 song 'Vogue'?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Bette Davis', '⬥ B:Rita Hayworth', '⬥ C:Fred Astaire', '⬥ D:Cary Grant'],
        "correct_answer": "Cary Grant"},
    {"question": "The military alert term 'DEFCON' is short for what?",
     "options": ['⬥ A:Defined Containment', '⬥ B:Defense Condition', '⬥ C:Deflected Contest', '⬥ D:Definite Conflict'],
     "correct_answer": "Defense Condition"},
    {"question": "Nicknamed 'Old Ironsides,' the U.S.S. Constitution is docked outside what city?",
     "options": ['⬥ A:Philadelphia', '⬥ B:Baltimore', '⬥ C:New York', '⬥ D:Boston'], "correct_answer": "Boston"},
    {"question": "Quoting economist Adam Smith, Napoleon dismissed England as 'nation of' what?",
     "options": ['⬥ A:Shopkeepers', '⬥ B:Haberdashers', '⬥ C:Fox hunters', '⬥ D:Carpenters'],
     "correct_answer": "Shopkeepers"},
    {"question": "The video game system Atari takes its name from a term used in what game?'50:50 lifeline used'",
     "options": ['⬥ A:Chinese checkers', '⬥ B:Parcheesi', '⬥ C:Mah-jongg', '⬥ D:Go'], "correct_answer": "Go"},
    {"question": "The 'D.C.' in the name of our nation's capital stands for 'District of' what?",
     "options": ['⬥ A:Columbia', '⬥ B:Chesapeake', '⬥ C:Cambridge', '⬥ D:Crooks'], "correct_answer": "Columbia"},
    {"question": "What rock group was nicknamed 'The Fab Four'?",
     "options": ['⬥ A:The Rolling Stones', '⬥ B:The Beatles', '⬥ C:The Who', '⬥ D:The Kinks'],
     "correct_answer": "The Beatles"},
    {"question": "Which of these parts of an oak tree contains most of its chlorophyll?",
     "options": ['⬥ A:Leaf', '⬥ B:Root', '⬥ C:Acorn', '⬥ D:Bark'], "correct_answer": "Leaf"},
    {"question": "What type of celestial body is often described as having a head and tail?",
     "options": ['⬥ A:Moon', '⬥ B:Star', '⬥ C:Black hole', '⬥ D:Comet'], "correct_answer": "Comet"},
    {
        "question": "In the U.S., what kind of omelet is traditionally served with chopped green pepper, onion, and tomato?",
        "options": ['⬥ A:Spanish', '⬥ B:French', '⬥ C:Italian', '⬥ D:German'], "correct_answer": "Spanish"},
    {"question": "'Tale as old as time' is the opening line of what Oscar-winning song?",
     "options": ['⬥ A:My Heart Will Go On', '⬥ B:Up Where We Belong', '⬥ C:Beauty and the Beast',
                 '⬥ D:A Whole New World'], "correct_answer": "Beauty and the Beast"},
    {
        "question": "In 1964, what gas company began a Christmas tradition when it released a toy truck bearing its logo?'Ask the Audience' lifeline used",
        "options": ['⬥ A:Amoco', '⬥ B:Hess', '⬥ C:Gulf', '⬥ D:Texaco'], "correct_answer": "Hess"},
    {"question": "In 1995, Air Force pilot Scott O'Grady was rescued six days after being shot down over what country?",
     "options": ['⬥ A:North Korea', '⬥ B:Iraq', '⬥ C:China', '⬥ D:Bosnia'], "correct_answer": "Bosnia"},
    {"question": "The 1987 movie 'The Princess Bride' features a criminal mastermind who often uses what word?",
     "options": ['⬥ A:Voluminous', '⬥ B:Fallacious', '⬥ C:Scrumptious', '⬥ D:Inconceivable'],
     "correct_answer": "Inconceivable"},
    {"question": "What kind of athletes participate in an event known as the 'Super G'?",
     "options": ['⬥ A:Skiers', '⬥ B:Ice skaters', '⬥ C:Cyclists', '⬥ D:Runners'], "correct_answer": "Skiers"},
    {
        "question": "What leader traditionally receives a ceremonial gold ring called the Ring of the Fisherman?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Shah of Iran', '⬥ B:Pope', '⬥ C:British Prime Minister', '⬥ D:Dalai Lama'],
        "correct_answer": "Pope"},
    {
        "question": "According to superstition, garlic worn around the neck protects a person from which of the following?",
        "options": ['⬥ A:Werewolves', '⬥ B:Bad weather', '⬥ C:Vampires', '⬥ D:Lasting relationships'],
        "correct_answer": "Vampires"},
    {"question": "Which of these insects is closely related to the grasshopper?",
     "options": ['⬥ A:Ladybug', '⬥ B:Wasp', '⬥ C:Butterfly', '⬥ D:Cricket'], "correct_answer": "Cricket"},
    {"question": "On July 20, 1969, Neil Armstrong famously said, “The Eagle has” what?",
     "options": ['⬥ A:Flown', '⬥ B:Landed', '⬥ C:Triumphed', '⬥ D:Arrived'], "correct_answer": "Landed"},
    {"question": "In the Bible, God reveals himself to Moses in the form of a what?",
     "options": ['⬥ A:Fruit tree', '⬥ B:Snake', '⬥ C:Burning bush', '⬥ D:Golden calf'],
     "correct_answer": "Burning bush"},
    {
        "question": "What credit car’s classic ads featured celebrities asking, “Do you know?”?“Ask the Audience” lifeline used.",
        "options": ['⬥ A:American Express', '⬥ B:MasterCard', '⬥ C:Visa', '⬥ D:Diner’s Club'],
        "correct_answer": "American Express"},
    {"question": "In 2001, Andre Agassi married what women’s tennis star in a price Las Vegas ceremony?",
     "options": ['⬥ A:Lindsay Davenport', '⬥ B:Jennifer Capriati', '⬥ C:Martina Hingis', '⬥ D:Steffi Graf'],
     "correct_answer": "Steffi Graf"},
    {"question": "The historic Ford’s Theatre is located in what U.S. city?",
     "options": ['⬥ A:Washington, D.C.', '⬥ B:Chicago', '⬥ C:Philadelphia', '⬥ D:Richmond'],
     "correct_answer": "Washington, D.C."},
    {"question": "American tycoon Andrew Carnegie made his fortune in what industry?",
     "options": ['⬥ A:Oil', '⬥ B:Fur', '⬥ C:Steel', '⬥ D:Real estate'], "correct_answer": "Steel"},
    {
        "question": "What John Waters movie was adapted into a hit Broadway musical that opened in 2002?'Phone-a-Friend' lifeline used",
        "options": ['⬥ A:Hairspray', '⬥ B:Cry-Baby', '⬥ C:Polyester', '⬥ D:Pink Flamingos'],
        "correct_answer": "Hairspray"},
    {"question": "What is the highest level in the Hindu caste system?’50:50' lifeline used",
     "options": ['⬥ A:Sudra', '⬥ B:Kshatriya', '⬥ C:Valsya', '⬥ D:Drahman'], "correct_answer": "Drahman"},
    {"question": "What type of animal is a snook?", "options": ['⬥ A:Bird', '⬥ B:Fish', '⬥ C:Lizard', '⬥ D:Insect'],
     "correct_answer": "Fish"},
    {"question": "What bird lays the largest egg?",
     "options": ['⬥ A:Ostrich', '⬥ B:Falcon', '⬥ C:Penguin', '⬥ D:NBC peacock'], "correct_answer": "Ostrich"},
    {"question": "According to legend, George Washington refused to lie about chopping down what kind of tree?",
     "options": ['⬥ A:Peach tree', '⬥ B:Willow tree', '⬥ C:Cherry tree', '⬥ D:Oak tree'],
     "correct_answer": "Cherry tree"},
    {"question": "In mathematics, what are classified as acute, obtuse, or right?",
     "options": ['⬥ A:Angles', '⬥ B:Bases', '⬥ C:Curves', '⬥ D:Axes'], "correct_answer": "Angles"},
    {"question": "What is the name of the substance that makes up the hard outer surface of a human tooth?",
     "options": ['⬥ A:Dentin', '⬥ B:Enamel', '⬥ C:Cementum', '⬥ D:Porcelain'], "correct_answer": "Enamel"},
    {"question": "On the game show 'Wheel of Fortune,' how much does it cost to buy a vowel?",
     "options": ['⬥ A:$50', '⬥ B:$100', '⬥ C:$250', '⬥ D:$500'], "correct_answer": "$250"},
    {"question": "Which of these musical instruments would most likely be played at a luau?",
     "options": ['⬥ A:Harp', '⬥ B:Ukulele', '⬥ C:Piano', '⬥ D:Hawaii Five-Oboe'], "correct_answer": "Ukulele"},
    {"question": "Which of the following is usually considered a 'red' meat?",
     "options": ['⬥ A:Pork', '⬥ B:Chicken', '⬥ C:Beef', '⬥ D:Turkey'], "correct_answer": "Beef"},
    {"question": "Geoffrey, the mascot of Toys 'R' Us, is what type of animal?",
     "options": ['⬥ A:Giraffe', '⬥ B:Jackal', '⬥ C:Gorilla', '⬥ D:Gerbil'], "correct_answer": "Giraffe"},
    {"question": "In a 1973 hit single, Elton John sings 'Goodbye' to what?",
     "options": ['⬥ A:Garden of Eden', '⬥ B:Neverland', '⬥ C:White Picket Fence', '⬥ D:Yellow Brick Road'],
     "correct_answer": "Yellow Brick Road"},
    {"question": "In a famous line from Shakespeare, what emotion is called the 'green-eyed monster'?",
     "options": ['⬥ A:Happiness', '⬥ B:Sympathy', '⬥ C:Remorse', '⬥ D:Jealousy'], "correct_answer": "Jealousy"},
    {"question": "By definition, a vintner is a person who makes or sells what?",
     "options": ['⬥ A:Candy', '⬥ B:Wine', '⬥ C:Mirrors', '⬥ D:Cheese'], "correct_answer": "Wine"},

]
